import "@/styles/globals.css";

import { cn } from "@/lib/utils";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import Header from "@/components/common/header";
import Providers from "./providers";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html
			lang="en"
			className={`${GeistMono.variable} ${GeistSans.variable}`}
			suppressHydrationWarning
		>
			<body className="flex min-h-screen flex-col font-sans md:max-w-7xl lg:mx-auto lg:flex-row">
				<Providers>
					<main
						className={cn(
							"relative flex flex-1 flex-col overflow-x-hidden border-border/50 border-x",
						)}
					>
						<Header />
						<div className="grid flex-1 grid-cols-1 lg:grid-cols-[32px_1fr_32px]">
							<div className="hidden w-full border-r bg-dashed opacity-75 lg:block" />
							<div className="relative col-span-1 px-3 lg:px-0">{children}</div>
							<div className="hidden w-full border-l bg-dashed opacity-75 lg:block" />
						</div>
					</main>
				</Providers>
			</body>
		</html>
	);
};

export default RootLayout;
